### ISSUE TITLE
Add 21 char limit for channel names

### ISSUE THREAD

**Issue by TimDurward** [TimDurward/terraform-provider-slack#1]

**Comment by NicoleYson** [comment]
The tag states help wanted, I added validation in `resource_channel.go` but am unable to push 😄 
`fatal: unable to access 'https://github.com/TimDurward/terraform-provider-slack.git/': The requested URL returned error: 403`

**Comment by TimDurward** [comment]
Thanks to @NicoleYson this is finished. Nice work 😎
