### ISSUE TITLE
0.12 compatibility

### ISSUE THREAD

**Issue by dsmith73** [TimDurward/terraform-provider-slack#19]
With the upgrade to terraform v0.12, I get the following error when I attempt to use this provider: 

```
Failed to instantiate provider "slack" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

The cursory research that I've done indicates that there will likely need to be an update to the provider for compatibility to v0.12

**Comment by TimDurward** [comment]
+1
0.12v is here, and we should really get this updated. 

Success Criteria for anyone that would like to take on this ticket:
1. Provider works in Terraform 0.12v environment
2. Has been tested
3. Update README and instructions

**Comment by chaspy** [comment]
Hello, @TimDurward 👋 
I'm interested in the task, I'd like to use this plugin with Terraform v0.12 😄 
Could you provide a guide for this task? I've never created a provider, but I'd like to contribute.

**Comment by chaspy** [comment]
I'll try 💪 
https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html

**Comment by chaspy** [comment]
It works https://github.com/TimDurward/terraform-provider-slack/pull/23
but statefile was not updated 😅 

1. build and move the binary

```
go build
mv terraform-provider-slack ~/.terraform.d/plugins/
```

2. Add files
3. init and plan and apply (The channel was created successfully)
4. state file is not updated

```
$ cat terraform.tfstate
{
  "version": 4,
  "terraform_version": "0.12.24",
  "serial": 2,
  "lineage": "adc98364-bca7-def4-1bdc-afe99d64de42",
  "outputs": {},
  "resources": []
}

$ cat terraform.tfstate.backup
{
  "version": 4,
  "terraform_version": "0.12.24",
  "serial": 1,
  "lineage": "adc98364-bca7-def4-1bdc-afe99d64de42",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "slack_channel",
      "name": "sre_alert_channel_test_chaspy",
      "provider": "provider.slack",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "channel_name": "sre-alert-channel-test-chaspy",
            "channel_purpose": null,
            "channel_topic": "test Alert channel for production test",
            "id": "C012R2Q2N8J"
          },
          "private": "bnVsbA=="
        }
      ]
    }
  ]
}
```

ah, the expected resource is shown in .backup 🤔

**Comment by TimDurward** [comment]
I'm also going to close #23 in favor of this Pull Request. Sorry @chaspy, I know you spent a little time on it, but you also inspired me to finish this up :).

### 0.12 compatibility is available here:
https://github.com/TimDurward/terraform-provider-slack/releases/tag/v0.2.0
