### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by nbirnel** [TimDurward/terraform-provider-slack#2]
```
make
==> Checking that code complies with gofmt requirements...
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
go install
# github.com/hashicorp/terraform/config
../../hashicorp/terraform/config/testing.go:9: t.Helper undefined (type *testing.T has no field or method Helper)
make: *** [Makefile:7: build] Error 2
```

**Comment by TimDurward** [comment]
@nbirnel 
Thanks I'll look into it, I always welcome other contributors too if you'd like to help!

**Comment by nbirnel** [comment]
@TimDurward I have no Go experience, but I *am* interested in this project - assuming it is maintained? 

My first PR was going to be adding explicit build instructions (``go get``prerequisites, etc), but then I hit the undefined error. :)

**Comment by TimDurward** [comment]
@nbirnel I wasn’t able to reproduce that issue on my mac. What’s your golang version and OS you’re running it on?

**Comment by TimDurward** [comment]
Closing for now. If anyone experiences further make failures please make a new issue.
