### ISSUE TITLE
Publish to Terraform Registry

### ISSUE THREAD

**Issue by richardj-bsquare** [TimDurward/terraform-provider-slack#28]
Great provider, we use it constantly to integrate our CI/CD system deploys with Slack.

Please consider adding this to the terraform registry directly, so we can invoke from Terraform Cloud, etc.

It has already been indirectly published (https://registry.terraform.io/providers/nlamirault/slack/latest) but it would be great to get it "directly from the horse's mouth" so to speak.

**Comment by richardj-bsquare** [comment]
Hmm, look like PR #27 When merged would address this!

**Comment by TimDurward** [comment]
Will be looking at this soon. Thank you for bringing it up!

**Comment by dimisjim** [comment]
Any update on this? @TimDurward

**Comment by TimDurward** [comment]
@richardj-bsquare / @dimisjim It's now published: https://registry.terraform.io/providers/TimDurward/slack/latest
