### ISSUE TITLE
Provide build against terraform 0.12 SDK

### ISSUE THREAD

**Issue by richardj-bsquare** [TimDurward/terraform-provider-slack#7]
terraform 0.12 has been released, and the provider protocol has changed requiring a new build and possibly some additional fixes.

**Comment by TimDurward** [comment]
Thanks for the update!

I'll try and take a look at this shortly @richardj-bsquare . If you'd like I can also assign to you if you were wanting to contribute.

**Comment by TimDurward** [comment]
Going to add `help-wanted` in case someone else would like to take a stab at 0.12 support. I haven't tested it with that version yet, but it would definitely be nice to have.

**Comment by TimDurward** [comment]
Fix has gone out:
#24

Latest release is here:
https://github.com/TimDurward/terraform-provider-slack/releases
